### ISSUE TITLE
Wrong feet placement

### ISSUE THREAD

**Issue by tkelestemur** [team-vigir/vigir_footstep_planning_core#3]
I followed the ros wiki and set `/vigir/terrain_classifier/set_point_cloud` to a 3D point cloud that I'm assembling from a lidar sensor. However, as can be seen in the screenshots below, footstep planner puts the feet inside the obstacles.

![screenshot from 2016-12-11 20 26 15](https://cloud.githubusercontent.com/assets/5513783/21085578/cc83f238-bfe1-11e6-8b17-90f47e419a3a.png)
![screenshot from 2016-12-11 20 26 31](https://cloud.githubusercontent.com/assets/5513783/21085577/cc82ed2a-bfe1-11e6-9a13-98e185d9345e.png)

What could be the reason of it?

**Comment by astumpf** [comment]
I'm pretty sure thats because your point cloud ist not dense (there are huge gaps between the voxels). Either collect more data or reduce the terrain model voxel resolution.
If the terrain model does not provide any 3D data of a region, the planner assumes incomplete world model representation and copies the alignment from previous footstep. That has been implemented this way as we would like to ensure to get any planning results in case of occlusions.
Either use grid map collision check additionally or use the return variable of the terrain model in the state generator. For latter just change the line https://github.com/team-vigir/vigir_footstep_planning_core/blob/master/vigir_footstep_planning_default_plugins/src/state_generator/expand_state_job.cpp#L43 to check the returned boolean value (true -> success).
